FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copiar todo o código-fonte do projeto
COPY . .

ENV NODE_ENV=development
ENV REACT_APP_BACKEND_URL=http://backend:8080

EXPOSE 3000

CMD ["npm", "start"] 