version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ecommerce-backend-dev
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-sa}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-password}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    networks:
      - ecommerce-network
    volumes:
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
      - gradle-cache:/root/.gradle
    healthcheck:
      test: ["CMD", "ls", "/app/gradlew"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ecommerce-frontend-dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - REACT_APP_BACKEND_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ecommerce-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  ecommerce-network:
    driver: bridge

volumes:
  gradle-cache:
  node_modules: 