version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ecommerce-frontend-1
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - REACT_APP_BACKEND_URL=http://gateway-service:8080
    depends_on:
      - gateway-service
    networks:
      - ecommerce-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - ecommerce-network

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network

  gateway-service:
    build: ./gateway-service
    ports:
      - "8090:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - ecommerce-network

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - mongodb
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATA_MONGODB_HOST: mongodb
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres
      - product-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
    networks:
      - ecommerce-network

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - postgres
      - rabbitmq
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_payment
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - ecommerce-network

  user-service:
    build: ./user-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_user
    networks:
      - ecommerce-network

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "50051:50051"
      - "5001:5001"
    depends_on:
      - eureka-server
    environment:
      EUREKA_SERVER: http://eureka-server:8761/eureka/
      SERVICE_IP: recommendation-service
    networks:
      - ecommerce-network

volumes:
  postgres-data:
  mongodb-data:

networks:
  ecommerce-network:
    driver: bridge 