server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://payment-service:8083
          predicates:
            - Path=/api/payments/**
        - id: user-service
          uri: http://user-service:8084
          predicates:
            - Path=/api/users/**, /api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    hostname: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway 