server:
  port: 8081

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ecommerce
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info 